
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '885CA03A1C554CBEC1560903CCA17454'
    
_lr_action_items = {'AND':([1,2,7,8,15,16,17,18,],[-3,-2,12,-5,-8,-7,-6,12,]),'IN':([3,4,6,14,],[10,-10,11,-9,]),'TOP':([0,12,13,],[6,6,6,]),'TRUE':([0,12,],[2,2,]),'FALSE':([0,12,13,],[8,8,8,]),'INTER':([3,4,14,],[9,-10,9,]),'$end':([5,8,15,16,17,19,],[0,-5,-8,-7,-6,-1,]),'ID':([0,9,10,11,12,13,],[4,4,15,17,4,4,]),'BOTTOM':([10,],[16,]),'IMPLIES':([1,2,7,8,15,16,17,18,],[-3,-2,13,-5,-8,-7,-6,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'term':([0,12,13,],[1,1,19,]),'concept':([0,9,12,13,],[3,14,3,3,]),'clause':([0,],[5,]),'prems':([0,12,],[7,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> clause","S'",1,None,None,None),
  ('clause -> prems IMPLIES term','clause',3,'p_clause_implies','hh_parser.py',31),
  ('prems -> TRUE','prems',1,'p_prems_trivial','hh_parser.py',35),
  ('prems -> term','prems',1,'p_prems_term','hh_parser.py',39),
  ('prems -> prems AND prems','prems',3,'p_prems_and','hh_parser.py',43),
  ('term -> FALSE','term',1,'p_term_trivial','hh_parser.py',47),
  ('term -> TOP IN ID','term',3,'p_top_in_term','hh_parser.py',51),
  ('term -> concept IN BOTTOM','term',3,'p_term_in_bot','hh_parser.py',55),
  ('term -> concept IN ID','term',3,'p_term_in','hh_parser.py',59),
  ('concept -> concept INTER concept','concept',3,'p_concept_inter','hh_parser.py',63),
  ('concept -> ID','concept',1,'p_concept_id','hh_parser.py',67),
]
